version: '3.7'

# Define services
services:
  # Database Service (MongoDB)
  mongodb_container:
    image: mongo:latest
    container_name: "mongodb"
    ports:
      - 27018:27017

  # App backend service
  app-server:
    # Configuration for building the docker image for the backend service
    build:
      context: curly-backend # Use an image built from the specified dockerfile in the `curly-backend` directory.
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # Forward the exposed port 8080 on the container to port 8080 on the host machine
    restart: always
    links:
      - mongodb_container
    depends_on:
      - mongodb_container # This service depends on MongoDB. Start that first.
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - backend
      - frontend

  # Frontend Service
  app-client:
    build:
      context: curly-frontend # Use an image built from the specified dockerfile in the `curly-frontend` directory.
      dockerfile: Dockerfile
      args:
        REACT_APP_API_BASE_URL: http://127.0.0.1:8080/api
    ports:
      - "9099:80" # Forward the exposed port 80 on the container to port 9090 on the host machine
    restart: always
    depends_on:
      - app-server
    networks:
      - frontend





# Networks to be created to facilitate communication between containers
networks:
  backend:
  frontend: